Development
VollyKor/axels-practice pull request #2
Opened 2021-05-11 04:50 UTC by VollyKor

2021-05-11 08:25 UTC, mike-gusiev requested changes

2021-05-11 08:25 UTC, mike-gusiev commented on .gitignore
>  npm-debug.log*
сделай bredcrumbs кликабельными. чтобы я мог переключаться между скринами:
https://take.ms/i11Ik

2021-05-11 08:25 UTC, mike-gusiev commented on .gitignore
> +.env
перед отправкой пул реквеста на ревью пересматривай свой пул реквест. и поправишь все что заметишь самостоятельно, до того как мне отправлять на ревью.

если видишь такую иконку, значит у этого файла не хватает переноса строки в конце.

2021-05-11 08:25 UTC, mike-gusiev commented on src/components/App.jsx
> +                    <Container className="p-3"></Container>
тег должен быть одинарным

2021-05-11 08:25 UTC, mike-gusiev commented on src/components/App.jsx
>  function App() {
используй краткую форму es6 функций без return, там где это возможно

2021-05-11 08:25 UTC, mike-gusiev commented on src/components/CartLink.jsx
> +import { CartWrapper, CartText, CartNotification } from "../styled/CartLink";
одинарные кавычки должны быть

2021-05-11 08:25 UTC, mike-gusiev commented on src/components/Navbar.jsx
> +import { CartLink } from "components";
- погрупируй импорты. сначала будут идти импорты библиотек, потом отступ, потом импорты компонентов, потом отступ, потом импорт всего остального
- одинарные кавычки

2021-05-11 08:25 UTC, mike-gusiev commented on src/components/Tooltip.jsx
> +        'Error, Some props are missing fro Tooltip'
опечатка

2021-05-11 08:25 UTC, mike-gusiev commented on src/helpers/requests.js
> +// export const getAddress = async (lat, lng) =>
не храни закомиченные куски кода в гите

2021-05-11 08:25 UTC, mike-gusiev commented on src/redux/reducers/order.js
> +import { createAction, createReducer } from '@reduxjs/toolkit';
структура редакса немного неправильная. избавься от папки reducers. и создай папку src/redux/ducks. и туда в отдельные файлы помести все екшены,редюсеры/саги и тд одним файлом. все что относиться к одному duck - должно быть в одном файле:
https://github.com/erikras/ducks-modular-redux

2021-05-11 08:25 UTC, mike-gusiev commented on src/styled/OrderSummary.js
> +    color: #757575;
- повыноси все цвета и media запросы в глобальные переменные

2021-05-11 08:25 UTC, mike-gusiev commented on src/styled/OrderSummary.js
> +    <div className="p-1">
не храни верстку в styled components. это должен быть отдельный компонент

2021-05-11 20:25 UTC, mike-gusiev requested changes

2021-05-11 20:25 UTC, mike-gusiev commented on src/components/GoodleModal.jsx
> +                {true && (
а зачем здесь проверка на true?

2021-05-11 20:25 UTC, mike-gusiev commented on src/components/GoodleModal.jsx
> +const containerStyle = {
назови переменную googleMapsStyles

2021-05-11 20:25 UTC, mike-gusiev commented on src/styled/CartLink.js
> +export const CartQuantyty = styled.p``;
опечатка

2021-05-11 20:25 UTC, mike-gusiev commented on src/styled/OrderNav.js
> +    /* margin-bottom: 20px;
закоменченный код не храни в гите. удали его

2021-05-11 20:25 UTC, mike-gusiev commented on src/styled/PaymentForm.js
> +    right: 0px;
возле нуля не ставиться px

2021-05-12 05:21 UTC, VollyKor commented on src/components/GoodleModal.jsx
> +                {true && (
заглушка, потенциально готовился к тому что бы данные будут асинхронно приходить

2021-05-12 05:37 UTC, merged